const mongoose = require('mongoose'),
    Schema = mongoose.Schema,   
    RBISModelSchema = require('./road-feature').RBISModelSchema,
    mongoosePaginate = require('mongoose-paginate')
    
const ROAD_ATTR_DET = ["RoadBridges", 
                    "RoadCarriageway", 
                    "RoadCauseways", 
                    "RoadCulverts", 
                    "RoadDitches", 
                    "RoadGuardrails", 
                    "RoadHazards",
                    "RoadJunctions", 
                    "RoadLightings", 
                    "RoadLocRefPoints", 
                    "RoadMarkings",
                    "RoadMedian", 
                    "RoadPlaceNames", 
                    "RoadShoulders", 
                    "RoadSideFriction", 
                    "RoadSideSlopes", 
                    "RoadSideWalks",
                    "RoadSigns", 
                    "RoadSpillways", 
                    "RoadStructures",
                    "RoadTraffic"]
const EXCLUDED_CONVERT_SHAPES = [
                "lastupdate_date",
                "updated_by",
                "created_by",
                "created_date",
                "file_attachment",
                "file_roadimages",
                "remarks_trail",
                ]                     
const ROAD_MODEL_STRUC = {      
    "RegionCode" : String, 
    "ProvinceCo" : String, 
    "CityMunCod" : String, 
    "R_ID" : String, 
    "R_NAME" : String, 
    "R_CLASS" : String, 
    "R_Importan" : String, 
    "Environmen" : String, 
    "RROW" : Number, 
    "RROWAcquir" : String, 
    "DirFlow" : String, 
    "Terrain" : String, 
    "Length" : Number, 
    "oldid" : String, 
    "RROW_acq_date": Date,
    "RROW_acq_cost":Number,
    "RROW_usefullife":Number,
    "remarks":String,
    "RoadBridges" : [RBISModelSchema.RoadBridges], 
    "RoadCarriageway" : [RBISModelSchema.RoadCarriageway], //Schema.Types.Mixed 
    "RoadCauseways" : [RBISModelSchema.RoadCauseways], 
    "RoadCulverts" : [RBISModelSchema.RoadCulverts], 
    "RoadDitches" : [RBISModelSchema.RoadDitches], 
    "RoadGuardrails" : [RBISModelSchema.RoadGuardrails], 
    "RoadHazards" : [RBISModelSchema.RoadHazards], 
    "RoadJunctions" : [RBISModelSchema.RoadJunctions], 
    "RoadLightings" : [RBISModelSchema.RoadLightings], 
    "RoadLocRefPoints" : [RBISModelSchema.RoadLocRefPoints], 
    "RoadMarkings" : [RBISModelSchema.RoadMarkings], 
    "RoadMedian" : [RBISModelSchema.RoadMedian], 
    "RoadPlaceNames" : [RBISModelSchema.RoadPlaceNames], 
    "RoadShoulders" : [RBISModelSchema.RoadShoulders], 
    "RoadSideFriction" : [Schema.Types.Mixed], 
    "RoadSideSlopes" : [RBISModelSchema.RoadSideSlopes], 
    "RoadSideWalks" : [RBISModelSchema.RoadSideWalks], 
    "RoadSigns" : [RBISModelSchema.RoadSigns], 
    "RoadSpillways" : [RBISModelSchema.RoadSpillways], 
    "RoadStructures" : [RBISModelSchema.RoadStructures],
    "RoadTraffic": [RBISModelSchema.RoadTraffic],
    "geometry" : Schema.Types.Mixed,
    "created_by":Schema.Types.Mixed,
    "updated_by":Schema.Types.Mixed,
    "lastupdate_date":{
                    type:Date,
                    default:new Date()
    },
    "created_date":{
        type:Date,
        default:new Date()
    },
    file_attachment:[Schema.Types.Mixed],
    file_roadimages:[Schema.Types.Mixed],
    remarks_trail:[Schema.Types.Mixed],
    status:String
}
const RoadsSchema = new Schema(ROAD_MODEL_STRUC,{ collection: 'Roads' });
RoadsSchema.set('toJSON', { getters: true, virtuals: true });
RoadsSchema.plugin(mongoosePaginate);
mongoose.model('Roads', RoadsSchema);
